export enum MemberPosition {
  DEVELOPMENT_LEAD = "DEVELOPMENT_LEAD",
  DEVELOPER = "DEVELOPER",
  STAFF = "STAFF",
  EMPLOYEE = "EMPLOYEE",
  CEO = "CEO",
  ADMIN = "ADMIN",
  FACTORY_MANAGER = "FACTORY_MANAGER"
}
