export enum MemberPosition {
  DEVELOPMENT_LEAD = "DEVELOPMENT_LEAD",
  DEVELOPER = "DEVELOPER",
  STAFF = "STAFF",
  EMPLOYEE = "EMPLOYEE",
  CEO = "CEO",
  ADMIN = "ADMIN",
  OPERATIONS_MANAGER = "OPERATIONS_MANAGER"
}
