export enum MemberRole {
  CEO = "CEO",
  ADMIN = "ADMIN",
  OPERATIONS_MANAGER = "OPERATIONS_MANAGER",
  FACTORY_MANAGER = "FACTORY_MANAGER",
  DEVELOPMENT_LEAD = "DEVELOPMENT_LEAD",
  DESIGNER = "DESIGNER",
  MARKETER = "MARKETER",
  DEVELOPER = "DEVELOPER",
  CONTENT_MANAGER = "CONTENT_MANAGER",
  STAFF = "STAFF"
}
