ALTER TABLE member_pre_registration
  ADD COLUMN IF NOT EXISTS age INTEGER,
  ADD COLUMN IF NOT EXISTS joined_at DATE,
  ADD COLUMN IF NOT EXISTS phone_number VARCHAR,
  ADD COLUMN IF NOT EXISTS duty_text VARCHAR;
